services:
  - type: web
    name: cs-master-syllabus
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false   # you will paste this manually in Render dashboard
